//--------------------------------------------------------------------------------
// Auto-generated by Migen (7507a2b) & LiteX (a742731d) on 2021-12-11 17:38:04
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef ROM_BASE
#define ROM_BASE 0x10000000L
#define ROM_SIZE 0x00020000
#endif

#ifndef SRAM_BASE
#define SRAM_BASE 0x11000000L
#define SRAM_SIZE 0x00002000
#endif

#ifndef MAIN_RAM_BASE
#define MAIN_RAM_BASE 0x80000000L
#define MAIN_RAM_SIZE 0x40000000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x12000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "ROM       0x10000000 0x20000 \nSRAM      0x11000000 0x2000 \nMAIN_RAM  0x80000000 0x40000000 \nCSR       0x12000000 0x10000 "
#endif
#endif
