//--------------------------------------------------------------------------------
// Auto-generated by Migen (7507a2b) & LiteX (a742731d) on 2021-12-11 17:38:04
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 100000000
#define CONFIG_CPU_HAS_INTERRUPT
#define CONFIG_CPU_RESET_ADDR 268435456
#define CONFIG_CPU_TYPE_ROCKET
#define CONFIG_CPU_VARIANT_LINUXD
#define CONFIG_CPU_HUMAN_NAME "RocketRV64[imac]"
#define CONFIG_CPU_NOP "nop"
#define CONFIG_WITH_BUILD_TIME
#define IRQ1_INTERRUPT 0
#define IRQ2_INTERRUPT 1
#define IRQ3_INTERRUPT 2
#define PCIE2WISHBONE_INTERRUPT 3
#define WISHBONE2PCIE_INTERRUPT 4
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "WISHBONE"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_CPU_HAS_DMA_BUS
#define TIMER0_INTERRUPT 1
#define UART_INTERRUPT 0

#endif
